---
namespace: dreknix
name: user
version: 1.0.0

readme: README.md

authors:
  - dreknix https://github.com/dreknix

description: Bunch of Ansible roles for user setup

license:
  - MIT

tags:
  - linux

dependencies: {}

repository: https://github.com/dreknix/ansible-collection-user

build_ignore: []
...
