---
# https://taskfile.dev

version: '3'

vars:
  PLAYBOOK: dreknix.user.playbook
  EXTRA_VARS: -e 'target=localhost'

tasks:

  versions:
    desc: Check versions of installed tools
    cmds:
      - ./scripts/check_versions.py

  lint:
    desc: Check syntax of the playbook
    cmds:
      - yamllint .
      - ansible-playbook {{.EXTRA_VARS}} --syntax-check {{.PLAYBOOK}}
      - ansible-lint --profile production

  check:
    desc: Run playbook {{.PLAYBOOK}} in check mode
    deps: [lint]
    cmds:
      - ansible-playbook --check {{.EXTRA_VARS}} {{.PLAYBOOK}}

  diff:
    desc: Run playbook {{.PLAYBOOK}} in check and diff mode
    deps: [lint]
    cmds:
      - ansible-playbook --check --diff {{.EXTRA_VARS}} {{.PLAYBOOK}}

  run:
    desc: Run playbook {{.PLAYBOOK}}
    deps: [lint]
    cmds:
      - ansible-playbook {{.EXTRA_VARS}} {{.PLAYBOOK}}

  run:bin:
    desc: Run {{.PLAYBOOK}} with tag bin
    deps: [lint]
    cmds:
      - ansible-playbook {{.EXTRA_VARS}} --tag user_bin {{.PLAYBOOK}}

  run:packages:
    desc: Run {{.PLAYBOOK}} with tag packages
    deps: [lint]
    cmds:
      - ansible-playbook {{.EXTRA_VARS}} --tag user_packages {{.PLAYBOOK}}

  molecule:lint:
    desc: Lint the playbook with Molecule
    cmds:
      - molecule lint

  molecule:test:
    desc: Test the playbook with Molecule
    cmds:
      # - molecule --debug converge
      # - molecule --debug idempotence
      - molecule test

...
