---

# Install all required packages

- name: Update apt
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == "Debian"

- name: Install all required packages
  become: true
  ansible.builtin.package:
    pkg:
      - ack-grep
      - apache2-utils
      - arp-scan
      - aspell
      - aspell-en
      - aspell-de
      - atop
      - bash
      - bash-completion
      - bat
      - bc
      - bitwise
      - bibclean
      - btop
      - cgdb
      - chktex
      - clang
      - clang-format
      - clang-tidy
      - cmake
      - cppcheck
      - curl
      - dmenu
      - direnv
      - dnsutils
      - dos2unix
      - duf
      - ethtool
      - fasd
      - fd-find
      - feh
      - flake8
      - fzf
      - gcc
      - g++
      - git
      - gitlint
      - gnuplot
      - golang
      - htop
      - httpie
      - imagemagick
      - inxi
      - ipcalc
      - iperf3
      - ipv6calc
      - iotop
      - jq
      - keepassxc
      - kpcli
      - lsof
      - make
      - manpages
      - manpages-dev
      # - mlocate
      - most
      - multitail
      - netcat-openbsd
      - neofetch
      # - newsboat
      - ncdu
      - nmap
      - nnn
      - octave
      - openssh-client
      - p7zip-full
      - patat
      - peco
      - pdftk
      - python3
      - python3-pip
      - python3-wheel
      - python3-venv
      - pwgen
      - ripgrep
      - rofi
      - shellcheck
      - silversearcher-ag
      - sshpass
      - stress
      - s-tui
      - subversion
      - tig
      - tldr
      - tmux
      - tree
      - unzip
      - vim
      # - vim-scripts
      - vim-gtk3
      - wget
      - xclip
      - xkcdpass
      - yamllint
      - zip
      - zsh

...
