---

bin_docker_credential_helpers_version: >-
  {{ lookup('ini', 'version section=docker-credential-helpers file={{ tools_version_file }}') }}

bin_docker_credential_helpers_github_repo_name: >-
  {{ lookup('ini', 'name section=docker-credential-helpers file={{ tools_version_file }}') }}

bin_docker_credential_helpers_os: linux

bin_docker_credential_helpers_arch: amd64

bin_docker_credential_helpers_url: "https://github.com/\
  {{ bin_docker_credential_helpers_github_repo_name }}/\
  releases/download/\
  v{{ bin_docker_credential_helpers_version }}/\
  docker-credential-pass-v{{ bin_docker_credential_helpers_version }}.\
  {{ bin_docker_credential_helpers_os }}-{{ bin_docker_credential_helpers_arch }}"

...
