---

bin_hadolint_version: >-
  {{ lookup('ini', 'version section=hadolint file={{ tools_version_file }}') }}

bin_hadolint_github_repo_name: >-
  {{ lookup('ini', 'name section=hadolint file={{ tools_version_file }}') }}

bin_hadolint_os: Linux

bin_hadolint_arch: x86_64

bin_hadolint_url: "https://github.com/\
  {{ bin_hadolint_github_repo_name }}/\
  releases/download/\
  v{{ bin_hadolint_version }}/\
  hadolint-{{ bin_hadolint_os }}-{{ bin_hadolint_arch }}"

...
