---

bin_minikube_version: >-
  {{ lookup('ini', 'version section=minikube file={{ tools_version_file }}') }}

bin_minikube_os: linux

bin_minikube_arch: amd64

bin_minikube_url: "https://storage.googleapis.com/minikube/releases/\
  v{{ bin_minikube_version }}/\
  minikube-{{ bin_minikube_os }}-{{ bin_minikube_arch }}"

...
