---

bin_pet_version: >-
  {{ lookup('ini', 'version section=pet file={{ tools_version_file }}') }}

bin_pet_github_repo_name: >-
  {{ lookup('ini', 'name section=pet file={{ tools_version_file }}') }}

bin_pet_os: linux

bin_pet_arch: amd64

bin_pet_url: "https://github.com/\
  {{ bin_pet_github_repo_name }}/\
  releases/download/\
  v{{ bin_pet_version }}/\
  pet_{{ bin_pet_version }}_\
  {{ bin_pet_os }}_{{ bin_pet_arch }}.tar.gz"

...
