---

bin_restic_version: >-
  {{ lookup('ini', 'version section=restic file={{ tools_version_file }}') }}

bin_restic_github_repo_name: >-
  {{ lookup('ini', 'name section=restic file={{ tools_version_file }}') }}

bin_restic_os: linux

bin_restic_arch: amd64

bin_restic_url: "https://github.com/\
  {{ bin_restic_github_repo_name }}/\
  releases/download/\
  v{{ bin_restic_version }}/\
  restic_\
  {{ bin_restic_version }}_{{ bin_restic_os }}_{{ bin_restic_arch }}.bz2"

...
