---

bin_taskwarrior_version: >-
  {{ lookup('ini', 'version section=taskwarrior file={{ tools_version_file }}') }}

bin_taskwarrior_github_repo_name: >-
  {{ lookup('ini', 'name section=taskwarrior file={{ tools_version_file }}') }}

bin_taskwarrior_url: "https://github.com/\
  {{ bin_taskwarrior_github_repo_name }}/\
  releases/download/\
  v{{ bin_taskwarrior_version }}/\
  task-{{ bin_taskwarrior_version }}.tar.gz"

bin_taskwarrior_tmp_path: >-
  /tmp/task-{{ bin_taskwarrior_version }}

...
