---

xdg_config_home_default:
    "{{ ansible_env.HOME }}/.config"
xdg_data_home_default:
    "{{ ansible_env.HOME }}/.local/share"
xdg_state_home_default:
    "{{ ansible_env.HOME }}/.local/state"

xdg_config_home:
    "{{ ansible_env.XDG_CONFIG_HOME | default(xdg_config_home_default) }}"
xdg_data_home:
    "{{ ansible_env.XDG_DATA_HOME | default(xdg_data_home_default) }}"
xdg_state_home:
    "{{ ansible_env.XDG_STATE_HOME | default(xdg_state_home_default) }}"

local_xdg_config_home_default:
    "{{ lookup('env', 'HOME') }}/.config"

local_xdg_config_home:
    "{{ lookup('env', 'XDG_CONFIG_HOME') or local_xdg_config_home_default }}"

local_xdg_data_home_default:
    "{{ lookup('env', 'HOME') }}/.local/share"

local_xdg_data_home:
    "{{ lookup('env', 'XDG_DATA_HOME') or local_xdg_data_home_default }}"

...
