---

driver:
  name: docker

platforms:
  - name: ubuntu
    image: ubuntu:22.04
  - name: debian
    image: debian:11

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: ansible

verifier:
  name: testinfra

...
