---

- name: Check if delta is installed
  ansible.builtin.stat:
    path: "{{ bin_delta_bin_path }}"
  register: bin_delta_binary

# - name: Debug Variables
#   ansible.builtin.debug:
#     msg:
#       - "delta binary exists {{ bin_delta_binary.stat }}"

- name: Check which version of delta is installed
  ansible.builtin.shell: |
    {{ bin_delta_bin_path }} --version
  register: bin_delta_version_check
  when: bin_delta_binary.stat.exists and bin_delta_binary.stat.executable
  changed_when: false

- name: Include installation of delta
  ansible.builtin.include_tasks: delta_install.yml
  vars:
    bin_delta_version_string: "delta {{ bin_delta_version }}"
  when: >
    not (bin_delta_binary.stat.exists and bin_delta_binary.stat.executable)
    or bin_delta_version_check.stdout is not defined
    or bin_delta_version_string not in bin_delta_version_check.stdout
    or bin_delta_force_install | bool

...
