---

- name: Check if direnv is installed
  ansible.builtin.stat:
    path: "{{ bin_direnv_bin_path }}"
  register: bin_direnv_binary

- name: Check which version of direnv is installed
  ansible.builtin.shell: |
    {{ bin_direnv_bin_path }} version
  register: bin_direnv_version_check
  check_mode: false
  when: >
    bin_direnv_binary.stat.exists
    and bin_direnv_binary.stat.executable
  changed_when: false

- name: Include installation of direnv
  ansible.builtin.include_tasks: direnv_install.yml
  vars:
    bin_direnv_version_string: >-
      {{ bin_direnv_version }}
  when: >
    not (bin_direnv_binary.stat.exists
        and bin_direnv_binary.stat.executable)
    or bin_direnv_version_check.stdout is not defined
    or bin_direnv_version_string != bin_direnv_version_check.stdout
    or bin_direnv_force_install | bool

...
