---

- name: Set GitHub repository name
  ansible.builtin.set_fact:
    github_repo_name: "{{ bin_direnv_github_repo_name }}"

- name: Download and install direnv
  ansible.builtin.get_url:
    force: true
    url: "{{ bin_direnv_url }}"
    dest: "{{ bin_direnv_bin_path }}"
    mode: 0755

...
