---

- name: Check if dive is installed
  ansible.builtin.stat:
    path: "{{ bin_dive_bin_path }}"
  register: bin_dive_binary

- name: Check which version of dive is installed
  ansible.builtin.shell: |
    {{ bin_dive_bin_path }} version
  register: bin_dive_version_check
  check_mode: false
  when: bin_dive_binary.stat.exists and bin_dive_binary.stat.executable
  changed_when: false

- name: Include installation of dive
  ansible.builtin.include_tasks: dive_install.yml
  vars:
    bin_dive_version_string: "dive {{ bin_dive_version }}"
  when: >
    not (bin_dive_binary.stat.exists and bin_dive_binary.stat.executable)
    or bin_dive_version_check.stdout is not defined
    or bin_dive_version_string not in bin_dive_version_check.stdout
    or bin_dive_force_install | bool

...
