---

- name: Set GitHub repository name
  ansible.builtin.set_fact:
    github_repo_name: "{{ bin_docker_credential_helpers_github_repo_name }}"

- name: Download and install docker-credential-helpers
  ansible.builtin.get_url:
    force: true
    url: "{{ bin_docker_credential_helpers_url }}"
    dest: "{{ bin_docker_credential_helpers_bin_path }}"
    mode: 0755

...
