---

- name: Set GitHub repository name
  ansible.builtin.set_fact:
    github_repo_name: "{{ bin_gopass_github_repo_name }}"

- name: Install gnupg2, git and rng-tools (needed by gopass)
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg2
    - git
    - rng-tools

- name: Create download target directory
  ansible.builtin.file:
    path: "{{ bin_gopass_tmp_path }}"
    state: directory
    mode: 0755

- name: Download and unarchive gopass into temporary location
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ bin_gopass_url }}"
    dest: "{{ bin_gopass_tmp_path }}"
    mode: 0755

- name: Move gopass binary into place
  ansible.builtin.copy:
    remote_src: true
    src: "{{ bin_gopass_tmp_path }}/gopass"
    dest: "{{ bin_gopass_bin_path }}"
    mode: 0755
  when: not ansible_check_mode

- name: Move gopass bash completion into place
  ansible.builtin.copy:
    remote_src: true
    src: "{{ bin_gopass_tmp_path }}/bash.completion"
    dest: "{{ user_bin_bash_completion_path }}/gopass.sh"
    mode: 0644
  when: not ansible_check_mode

- name: Remove downloaded target directory
  ansible.builtin.file:
    path: "{{ bin_gopass_tmp_path }}"
    state: absent

...
