---

- name: Set GitHub repository name
  ansible.builtin.set_fact:
    github_repo_name: "{{ bin_gopass_jsonapi_github_repo_name }}"

- name: Create download target directory
  ansible.builtin.file:
    path: "{{ bin_gopass_jsonapi_tmp_path }}"
    state: directory
    mode: 0755

- name: Download and unarchive gopass-jsonapi into temporary location
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ bin_gopass_jsonapi_url }}"
    dest: "{{ bin_gopass_jsonapi_tmp_path }}"
    mode: 0755

- name: Move gopass-jsonapi binary into place
  ansible.builtin.copy:
    remote_src: true
    src: "{{ bin_gopass_jsonapi_tmp_path }}/gopass-jsonapi"
    dest: "{{ bin_gopass_jsonapi_bin_path }}"
    mode: 0755

- name: Remove downloaded target directory
  ansible.builtin.file:
    path: "{{ bin_gopass_jsonapi_tmp_path }}"
    state: absent

...
