---

- name: Check if gopass-jsonapi is installed
  ansible.builtin.stat:
    path: "{{ bin_gopass_jsonapi_bin_path }}"
  register: bin_gopass_jsonapi_binary

- name: Check which version of gopass-jsonapi is installed
  ansible.builtin.shell: |
    {{ bin_gopass_jsonapi_bin_path }} --version
  register: bin_gopass_jsonapi_version_check
  when: >
    bin_gopass_jsonapi_binary.stat.exists
    and bin_gopass_jsonapi_binary.stat.executable
  changed_when: false
  failed_when: bin_gopass_jsonapi_version_check.rc >= 2

- name: Include installation of gopass-jsonapi
  ansible.builtin.include_tasks: gopass_jsonapi_install.yml
  vars:
    bin_gopass_jsonapi_version_string: >-
      gopass-jsonapi version {{ bin_gopass_jsonapi_version }}
  when: >
    not (bin_gopass_jsonapi_binary.stat.exists
        and bin_gopass_jsonapi_binary.stat.executable)
    or bin_gopass_jsonapi_version_check.stdout is not defined
    or (("Failed to initialize gopass API:"
        not in bin_gopass_jsonapi_version_check.stdout)
        and (bin_gopass_jsonapi_version_string
        != bin_gopass_jsonapi_version_check.stdout))
    or bin_gopass_jsonapi_force_install | bool

...
