---

- name: Set GitHub repository name
  ansible.builtin.set_fact:
    github_repo_name: "{{ bin_hadolint_github_repo_name }}"

- name: Download and install hadolint
  ansible.builtin.get_url:
    force: true
    url: "{{ bin_hadolint_url }}"
    dest: "{{ bin_hadolint_bin_path }}"
    mode: 0755

...
