---

- name: Check binary version - {{ binary }}
  ansible.builtin.include_tasks: install_internal_check.yml
  when: not force_install | default(false) | bool

- name: Install binary from archive - {{ binary }}
  ansible.builtin.include_tasks: install_internal_archive.yml
  when: >
    not (bin_binary.stat.exists and bin_binary.stat.executable)
    or bin_binary_version.stdout is not defined
    or version_string not in bin_binary_version.stdout
    or force_install | default(false) | bool

- name: Execute after commands - {{ binary }}
  ansible.builtin.include_tasks: install_internal_after.yml
  when: >
    after_cmds is defined and (
      not (bin_binary.stat.exists and bin_binary.stat.executable)
      or bin_binary_version.stdout is not defined
      or version_string not in bin_binary_version.stdout
      or force_install | default(false) | bool
    )

- name: Generate bash completion - {{ binary }}
  ansible.builtin.include_tasks: install_internal_completion.yml
  when: >
    generate_completion is defined and (
      not (bin_binary.stat.exists and bin_binary.stat.executable)
      or bin_binary_version.stdout is not defined
      or version_string not in bin_binary_version.stdout
      or force_install | default(false) | bool
    )

...
