---

- name: Set GitHub repository name
  ansible.builtin.set_fact:
    github_repo_name: "{{ bin_lazygit_github_repo_name }}"

- name: Create download target directory
  ansible.builtin.file:
    path: "{{ bin_lazygit_tmp_path }}"
    state: directory
    mode: 0755

- name: Download and unarchive lazygit into temporary location
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ bin_lazygit_url }}"
    dest: "{{ bin_lazygit_tmp_path }}"
    mode: 0755

- name: Move lazygit binary into place
  ansible.builtin.copy:
    remote_src: true
    src: "{{ bin_lazygit_tmp_path }}/lazygit"
    dest: "{{ bin_lazygit_bin_path }}"
    mode: 0755
  when: not ansible_check_mode

- name: Remove downloaded target directory
  ansible.builtin.file:
    path: "{{ bin_lazygit_tmp_path }}"
    state: absent

...
