---

- name: Check if lazygit is installed
  ansible.builtin.stat:
    path: "{{ bin_lazygit_bin_path }}"
  register: bin_lazygit_binary

- name: Check which version of lazygit is installed
  ansible.builtin.shell: |
    {{ bin_lazygit_bin_path }} --version
  register: bin_lazygit_version_check
  check_mode: false
  when: >
    bin_lazygit_binary.stat.exists
    and bin_lazygit_binary.stat.executable
  changed_when: false

- name: Include installation of lazygit
  ansible.builtin.include_tasks: lazygit_install.yml
  vars:
    bin_lazygit_version_string: ", version={{ bin_lazygit_version }}, "
  when: >
    not (bin_lazygit_binary.stat.exists and bin_lazygit_binary.stat.executable)
    or bin_lazygit_version_check.stdout is not defined
    or bin_lazygit_version_string not in bin_lazygit_version_check.stdout
    or bin_lazygit_force_install | bool

...
