---

- name: Check binary version - taskwarrior
  ansible.builtin.include_tasks: install_internal_check.yml
  vars:
    binary: "taskwarrior"
    version_args: "--version"
  when: not force_install | default(false) | bool

- name: Include binary from archive - taskwarrior
  ansible.builtin.include_tasks: main_taskwarrior_install.yml
  vars:
    version_string: "x {{ bin_taskwarrior_version }}"
  when: >
    not (bin_binary.stat.exists and bin_binary.stat.executable)
    or bin_binary_version.stdout is not defined
    or version_string not in bin_binary_version.stdout
    or force_install | default(false) | bool

...
