---

#
# Use import to inheritance the 'tags'
#

- name: Creates bin directory
  ansible.builtin.file:
    path: "{{ default_bin_path | default(bin_user_path, true) }}"
    state: directory
    mode: u=rwx,go=rx

- name: Creates bash completion directory
  ansible.builtin.file:
    path: "{{ bin_bash_completion_path }}"
    state: directory
    mode: u=rwx,go=rx

- name: Update apt
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == "Debian"

- name: Include task for installing delta
  ansible.builtin.import_tasks: main_delta.yml
  tags: user_bin_delta

- name: Include task for installing direnv
  ansible.builtin.import_tasks: main_direnv.yml
  tags: user_bin_direnv

- name: Include task for installing dive
  ansible.builtin.import_tasks: main_dive.yml
  tags: user_bin_dive

- name: Include task for installing docker-credential-helpers
  ansible.builtin.import_tasks: main_docker-credential-helpers.yml
  tags: user_bin_docker-credential-helpers

- name: Include task for installing gopass
  ansible.builtin.import_tasks: main_gopass.yml
  tags: user_bin_gopass

- name: Include task for installing gopass-jsonapi
  ansible.builtin.import_tasks: main_gopass_jsonapi.yml
  tags: user_bin_gopass_jsonapi

- name: Include task for installing hadolint
  ansible.builtin.import_tasks: main_hadolint.yml
  tags: user_bin_hadolint

- name: Include task for installing KeePassXC
  ansible.builtin.import_tasks: main_keepassxc.yml
  tags: user_bin_keepassxc

- name: Include task for installing kubectl
  ansible.builtin.import_tasks: main_kubectl.yml
  tags: user_bin_kubectl

- name: Include task for installing lazydocker
  ansible.builtin.import_tasks: main_lazydocker.yml
  tags: user_bin_lazydocker

- name: Include task for installing lazygit
  ansible.builtin.import_tasks: main_lazygit.yml
  tags: user_bin_lazygit

- name: Include task for installing micro
  ansible.builtin.import_tasks: main_micro.yml
  tags: user_bin_micro

- name: Include task for installing minikube
  ansible.builtin.import_tasks: main_minikube.yml
  tags: user_bin_minikube

- name: Include task for installing neovim
  ansible.builtin.import_tasks: main_neovim.yml
  tags: user_bin_neovim

- name: Include task for installing pet
  ansible.builtin.import_tasks: main_pet.yml
  tags: user_bin_pet

- name: Include task for installing restic
  ansible.builtin.import_tasks: main_restic.yml
  tags: user_bin_restic

- name: Include task for installing sqlightbrowser
  ansible.builtin.import_tasks: main_sqlightbrowser.yml
  tags: user_bin_sqlightbrowser

- name: Include task for installing task
  ansible.builtin.import_tasks: main_task.yml
  tags: user_bin_task

- name: Include task for installing taskwarrior
  ansible.builtin.import_tasks: main_taskwarrior.yml
  tags: user_bin_taskwarrior

...
