---

- name: Include task for installing docker-credential-helpers
  ansible.builtin.import_tasks: install_binary.yml
  vars:
    binary: "docker-credential-helpers"
    version_args: "version"
    version_string: >-
      docker-credential-pass (github.com/docker/docker-credential-helpers) v{{ bin_docker_credential_helpers_version }}
    url: "{{ bin_docker_credential_helpers_url }}"

- name: Deploy wrapper docker-credential-gopass
  ansible.builtin.copy:
    src: docker-credential-helpers/docker-credential-gopass
    dest: "{{ default_bin_path | default(bin_user_path, true) }}/docker-credential-gopass"
    mode: u=rwx,go=rx

- name: Deploy wrapper pass
  ansible.builtin.copy:
    src: docker-credential-helpers/pass
    dest: "{{ default_bin_path | default(bin_user_path, true) }}/pass"
    mode: u=rwx,go=rx

- name: Ensure Docker directory
  ansible.builtin.file:
    path: ~/.docker
    state: directory
    mode: u=rwx,go=rx

- name: Touch Docker config.json
  ansible.builtin.file:
    path: ~/.docker/config.json
    state: touch
    mode: u=rw,go=r
    modification_time: preserve
    access_time: preserve

- name: Load Docker config.json
  ansible.builtin.slurp:
    src: ~/.docker/config.json
  register: bin_docker_imported_vars
  ignore_errors: true

- name: Append credStore "gopass" to Docker config
  ansible.builtin.set_fact:
    bin_docker_imported_vars: >-
      {{ bin_docker_imported_vars.content |
      b64decode |
      default('{}', true) |
      from_json |
      combine({'credStore': 'gopass'}) }}

- name: Write Docker config.json
  ansible.builtin.copy:
    content: '{{ bin_docker_imported_vars | to_nice_json }}'
    dest: ~/.docker/config.json
    mode: u=rw,go=r

...
