---

- name: Set GitHub repository name
  ansible.builtin.set_fact:
    github_repo_name: "{{ bin_neovim_github_repo_name }}"

- name: Download and install neovim
  ansible.builtin.get_url:
    force: true
    url: "{{ bin_neovim_url }}"
    dest: "{{ bin_neovim_bin_path }}"
    mode: 0755

...
