---

- name: Check if pet is installed
  ansible.builtin.stat:
    path: "{{ bin_pet_bin_path }}"
  register: bin_pet_binary

- name: Check which version of pet is installed
  ansible.builtin.shell: |
    {{ bin_pet_bin_path }} version
  register: bin_pet_version_check
  check_mode: false
  when: bin_pet_binary.stat.exists and bin_pet_binary.stat.executable
  changed_when: false

- name: Include installation of pet
  ansible.builtin.include_tasks: pet_install.yml
  vars:
    bin_pet_version_string: "pet version {{ bin_pet_version }}"
  when: >
    not (bin_pet_binary.stat.exists and bin_pet_binary.stat.executable)
    or bin_pet_version_check.stdout is not defined
    or bin_pet_version_string not in bin_pet_version_check.stdout
    or bin_pet_force_install | bool

...
