---

- name: Set GitHub repository name
  ansible.builtin.set_fact:
    github_repo_name: "{{ bin_restic_github_repo_name }}"

- name: Install fuse and bzip2 (needed by restic)
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - fuse3
    - bzip2

- name: Download restic into temporary location
  ansible.builtin.get_url:
    url: "{{ bin_restic_url }}"
    dest: "{{ bin_restic_tmp_path }}.bz2"
    mode: 0600

- name: Extract restic
  ansible.builtin.command: >-
    bzip2 -d "{{ bin_restic_tmp_path }}.bz2"
  args:
    creates: "{{ bin_restic_tmp_path }}"

- name: Move restic binary into place
  ansible.builtin.copy:
    remote_src: true
    src: "{{ bin_restic_tmp_path }}"
    dest: "{{ bin_restic_bin_path }}"
    mode: 0755
  when: not ansible_check_mode

- name: Remove downloaded file
  ansible.builtin.file:
    path: "{{ bin_restic_tmp_path }}"
    state: absent

- name: Create restic bash completion
  ansible.builtin.command: >-
    {{ bin_restic_bin_path }} generate --bash-completion {{ user_bin_bash_completion_path }}/restic.sh
  args:
    creates: "{{ user_bin_bash_completion_path }}/restic.sh"


...
