---

- name: Check if superpet is installed
  ansible.builtin.stat:
    path: "{{ bin_superpet_bin_path }}"
  register: bin_superpet_binary

- name: Check which version of superpet is installed
  ansible.builtin.shell: |
    {{ bin_superpet_bin_path }} version
  register: bin_superpet_version_check
  check_mode: false
  when: bin_superpet_binary.stat.exists and bin_superpet_binary.stat.executable
  changed_when: false

- name: Include installation of superpet
  ansible.builtin.include_tasks: superpet_install.yml
  vars:
    bin_superpet_version_string: "pet version {{ bin_superpet_version }}"
  when: >
    not (bin_superpet_binary.stat.exists and bin_superpet_binary.stat.executable)
    or bin_superpet_version_check.stdout is not defined
    or bin_superpet_version_string not in bin_superpet_version_check.stdout
    or bin_superpet_force_install | bool

...
