---

- name: Check if taskwarrior is installed
  ansible.builtin.stat:
    path: "{{ bin_taskwarrior_bin_path }}"
  register: bin_taskwarrior_binary

- name: Check which version of taskwarrior is installed
  ansible.builtin.shell: |
    {{ bin_taskwarrior_bin_path }} --version
  register: bin_taskwarrior_version_check
  when: >
    bin_taskwarrior_binary.stat.exists
    and bin_taskwarrior_binary.stat.executable
  changed_when: false

- name: Include installation of taskwarrior
  ansible.builtin.include_tasks: taskwarrior_install.yml
  vars:
    bin_taskwarrior_version_string: "{{ bin_taskwarrior_version }}"
  when: >
    not (bin_taskwarrior_binary.stat.exists and bin_taskwarrior_binary.stat.executable)
    or bin_taskwarrior_version_check.stdout is not defined
    or bin_taskwarrior_version_string != bin_taskwarrior_version_check.stdout
    or bin_taskwarrior_force_install | bool

...
