---

- name: Set GitHub repository name
  ansible.builtin.set_fact:
    github_repo_name: "{{ bin_task_github_repo_name }}"

- name: Create download target directory
  ansible.builtin.file:
    path: "{{ bin_task_tmp_path }}"
    state: directory
    mode: 0755

- name: Download and unarchive task into temporary location
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ bin_task_url }}"
    dest: "{{ bin_task_tmp_path }}"
    mode: 0755

- name: Move task binary into place
  ansible.builtin.copy:
    remote_src: true
    src: "{{ bin_task_tmp_path }}/task"
    dest: "{{ bin_task_bin_path }}"
    mode: 0755

- name: Move task bash completion into place
  ansible.builtin.copy:
    remote_src: true
    src: "{{ bin_task_tmp_path }}/completion/bash/task.bash"
    dest: "{{ user_bin_bash_completion_path }}/task.sh"
    mode: 0644

- name: Remove downloaded target directory
  ansible.builtin.file:
    path: "{{ bin_task_tmp_path }}"
    state: absent

...
