---

- name: Check if task is installed
  ansible.builtin.stat:
    path: "{{ bin_task_bin_path }}"
  register: bin_task_binary

- name: Check which version of task is installed
  ansible.builtin.shell: |
    {{ bin_task_bin_path }} --version
  register: bin_task_version_check
  when: >
    bin_task_binary.stat.exists
    and bin_task_binary.stat.executable
  changed_when: false

- name: Include installation of task
  ansible.builtin.include_tasks: task_install.yml
  vars:
    bin_task_version_string: "Task version: v{{ bin_task_version }}"
  when: >
    not (bin_task_binary.stat.exists and bin_task_binary.stat.executable)
    or bin_task_version_check.stdout is not defined
    or bin_task_version_string not in bin_task_version_check.stdout
    or bin_task_force_install | bool

...
