---

bin_direnv_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_direnv_bin_path: >-
  {{ default_bin_path | default(bin_user_path, true) }}/direnv

bin_direnv_version: >-
  {{ lookup('ini', 'version section=direnv file={{ tools_version_file }}') }}

bin_direnv_github_repo_name: >-
  {{ lookup('ini', 'name section=direnv file={{ tools_version_file }}') }}

bin_direnv_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_direnv_arch: >-
  {{ default_bin_arch | default('amd64', true) }}

bin_direnv_url: "{{ github_release_download }}/\
  v{{ bin_direnv_version }}/\
  direnv.{{ bin_direnv_os }}-{{ bin_direnv_arch }}"

...
