---

bin_dive_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_dive_bin_path: >-
  {{ default_bin_path | default(bin_user_path, true) }}/dive

bin_dive_version: >-
  {{ lookup('ini', 'version section=dive file={{ tools_version_file }}') }}

bin_dive_github_repo_name: >-
  {{ lookup('ini', 'name section=dive file={{ tools_version_file }}') }}

bin_dive_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_dive_arch: >-
  {{ default_bin_arch | default('amd64', true) }}

bin_dive_url: "{{ github_release_download }}/\
  v{{ bin_dive_version }}/\
  dive_{{ bin_dive_version }}_\
  {{ bin_dive_os }}_{{ bin_dive_arch }}.tar.gz"

bin_dive_tmp_path: >-
  /tmp/dive_{{ bin_dive_version }}_{{ bin_dive_os }}_{{ bin_dive_arch }}

...
