---

bin_docker_credential_helpers_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_docker_credential_helpers_bin_path: >-
  {{ default_bin_path | default(bin_user_path, true) }}/docker-credential-pass

bin_docker_credential_helpers_version: >-
  {{ lookup('ini', 'version section=docker-credential-helpers file={{ tools_version_file }}') }}

bin_docker_credential_helpers_github_repo_name: >-
  {{ lookup('ini', 'name section=docker-credential-helpers file={{ tools_version_file }}') }}

bin_docker_credential_helpers_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_docker_credential_helpers_arch: >-
  {{ default_bin_arch | default('amd64', true) }}

bin_docker_credential_helpers_url: "{{ github_release_download }}/\
  v{{ bin_docker_credential_helpers_version }}/\
  docker-credential-pass-v{{ bin_docker_credential_helpers_version }}.\
  {{ bin_docker_credential_helpers_os }}-{{ bin_docker_credential_helpers_arch }}"

...
