---

bin_gopass_jsonapi_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_gopass_jsonapi_bin_path: >-
  {{ default_bin_path | default('~/bin', true) }}/gopass-jsonapi

bin_gopass_jsonapi_version: >-
  {{ lookup('ini', 'version section=gopass-jsonapi file={{ tools_version_file }}') }}

bin_gopass_jsonapi_github_repo_name: >-
  {{ lookup('ini', 'name section=gopass-jsonapi file={{ tools_version_file }}') }}

bin_gopass_jsonapi_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_gopass_jsonapi_arch: >-
  {{ default_bin_arch | default('amd64', true) }}

bin_gopass_jsonapi_url: "{{ github_release_download }}/\
  v{{ bin_gopass_jsonapi_version }}/\
  gopass-jsonapi-\
  {{ bin_gopass_jsonapi_version }}-\
  {{ bin_gopass_jsonapi_os }}-{{ bin_gopass_jsonapi_arch }}.tar.gz"

bin_gopass_jsonapi_tmp_path: >-
  /tmp/gopass_{{ bin_gopass_jsonapi_version }}

...
