---

bin_kubectl_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_kubectl_bin_path: >-
  {{ default_bin_path | default(bin_user_path, true) }}/kubectl

bin_kubectl_version: >-
  {{ lookup('ini', 'version section=kubectl file={{ tools_version_file }}') }}

bin_kubectl_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_kubectl_arch: >-
  {{ default_bin_arch | default('amd64', true) }}

bin_kubectl_url: "https://dl.k8s.io/release/\
  v{{ bin_kubectl_version }}/\
  bin/{{ bin_kubectl_os }}/{{ bin_kubectl_arch }}"

bin_kubectl_tmp_path: >-
  /tmp/kubectl-v{{ bin_kubectl_version }}-{{ bin_kubectl_os }}-{{ bin_kubectl_arch }}

...
