---

bin_lazygit_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_lazygit_bin_path: >-
  {{ default_bin_path | default('~/bin', true) }}/lazygit

bin_lazygit_version: >-
  {{ lookup('ini', 'version section=lazygit file={{ tools_version_file }}') }}

bin_lazygit_github_repo_name: >-
  {{ lookup('ini', 'name section=lazygit file={{ tools_version_file }}') }}

bin_lazygit_os: >-
  {{ default_bin_os | default('Linux', true) }}

bin_lazygit_arch: >-
  {{ default_bin_arch | default('x86_64', true) }}

bin_lazygit_url: "{{ github_release_download }}/\
  v{{ bin_lazygit_version }}/\
  lazygit_{{ bin_lazygit_version }}_{{ bin_lazygit_os }}_{{ bin_lazygit_arch }}.tar.gz"

bin_lazygit_tmp_path: >-
  /tmp/lazygit_{{ bin_lazygit_version }}

...
