---

bin_lazydocker_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_lazydocker_bin_path: >-
  {{ default_bin_path | default('~/bin', true) }}/lazydocker

bin_lazydocker_version: >-
  {{ lookup('ini', 'version section=lazydocker file={{ tools_version_file }}') }}

bin_lazydocker_github_repo_name: >-
  {{ lookup('ini', 'name section=lazydocker file={{ tools_version_file }}') }}

bin_lazydocker_os: >-
  {{ default_bin_os | default('Linux', true) }}

bin_lazydocker_arch: >-
  {{ default_bin_arch | default('x86_64', true) }}

bin_lazydocker_url: "{{ github_release_download }}/\
  v{{ bin_lazydocker_version }}/\
  lazydocker_{{ bin_lazydocker_version }}_{{ bin_lazydocker_os }}_{{ bin_lazydocker_arch }}.tar.gz"

bin_lazydocker_tmp_path: >-
  /tmp/lazydocker_{{ bin_lazydocker_version }}

...
