---

bin_micro_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_micro_bin_path: >-
  {{ default_bin_path | default(bin_user_path, true) }}/micro

bin_micro_version: >-
  {{ lookup('ini', 'version section=micro file={{ tools_version_file }}') }}

bin_micro_github_repo_name: >-
  {{ lookup('ini', 'name section=micro file={{ tools_version_file }}') }}

bin_micro_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_micro_arch: >-
  {{ default_bin_arch | default('64', true) }}

bin_micro_url: "{{ github_release_download }}/\
  v{{ bin_micro_version }}/\
  micro-{{ bin_micro_version }}-\
  {{ bin_micro_os }}{{ bin_micro_arch }}-static.tar.gz"

bin_micro_tmp_path: >-
  /tmp/micro-{{ bin_micro_version }}

...
