---

bin_minikube_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_minikube_bin_path: >-
  {{ default_bin_path | default('~/bin', true) }}/minikube

bin_minikube_version: >-
  {{ lookup('ini', 'version section=minikube file={{ tools_version_file }}') }}

bin_minikube_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_minikube_arch: >-
  {{ default_bin_arch | default('amd64', true) }}

bin_minikube_url: "https://storage.googleapis.com/minikube/releases/\
  v{{ bin_minikube_version }}/\
  minikube-{{ bin_minikube_os }}-{{ bin_minikube_arch }}"

bin_minikube_tmp_path: >-
  /tmp/minikube-v{{ bin_minikube_version }}-{{ bin_minikube_os }}-{{ bin_minikube_arch }}

...
