---

bin_restic_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_restic_bin_path: >-
  {{ default_bin_path | default(bin_user_path, true) }}/restic

bin_restic_version: >-
  {{ lookup('ini', 'version section=restic file={{ tools_version_file }}') }}

bin_restic_github_repo_name: >-
  {{ lookup('ini', 'name section=restic file={{ tools_version_file }}') }}

bin_restic_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_restic_arch: >-
  {{ default_bin_arch | default('amd64', true) }}

bin_restic_url: "{{ github_release_download }}/\
  v{{ bin_restic_version }}/\
  restic_\
  {{ bin_restic_version }}_{{ bin_restic_os }}_{{ bin_restic_arch }}.bz2"

bin_restic_tmp_path: >-
  /tmp/restic_{{ bin_restic_version }}

...
