---

bin_superpet_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_superpet_bin_path: >-
  {{ default_bin_path | default('~/bin', true) }}/superpet

bin_superpet_version: >-
  {{ lookup('ini', 'version section=superpet file={{ tools_version_file }}') }}

bin_superpet_github_repo_name: >-
  {{ lookup('ini', 'name section=superpet file={{ tools_version_file }}') }}

bin_superpet_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_superpet_arch: >-
  {{ default_bin_arch | default('amd64', true) }}

bin_superpet_url: "{{ github_release_download }}/\
  v{{ bin_superpet_version }}/\
  superpet_{{ bin_superpet_version }}_\
  {{ bin_superpet_os }}_{{ bin_superpet_arch }}.tar.gz"

bin_superpet_tmp_path: >-
  /tmp/superpet_{{ bin_superpet_version }}_{{ bin_superpet_os }}_{{ bin_superpet_arch }}

...
