---

bin_task_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_task_bin_path: >-
  {{ default_bin_path | default('~/bin', true) }}/task

bin_task_version: >-
  {{ lookup('ini', 'version section=task file={{ tools_version_file }}') }}

bin_task_github_repo_name: >-
  {{ lookup('ini', 'name section=task file={{ tools_version_file }}') }}

bin_task_os: >-
  {{ default_bin_os | default('linux', true) }}

bin_task_arch: >-
  {{ default_bin_arch | default('amd64', true) }}

bin_task_url: "{{ github_release_download }}/\
  v{{ bin_task_version }}/\
  task_{{ bin_task_os }}_{{ bin_task_arch }}.tar.gz"

bin_task_tmp_path: >-
  /tmp/task_{{ bin_task_version }}

...
