---

bin_taskwarrior_force_install: >-
  {{ default_bin_force_install | default('false', true) }}

bin_taskwarrior_bin_path: >-
  {{ default_bin_path | default('~/bin', true) }}/taskwarrior

bin_taskwarrior_version: >-
  {{ lookup('ini', 'version section=taskwarrior file={{ tools_version_file }}') }}

bin_taskwarrior_github_repo_name: >-
  {{ lookup('ini', 'name section=taskwarrior file={{ tools_version_file }}') }}

bin_taskwarrior_url: "{{ github_release_download }}/\
  v{{ bin_taskwarrior_version }}/\
  task-{{ bin_taskwarrior_version }}.tar.gz"

bin_taskwarrior_tmp_path: >-
  /tmp/task-{{ bin_taskwarrior_version }}

...
