---

#
# Configure local user
#

- name: Setup local user
  hosts: '{{ target | default("all") }}'
  gather_facts: true

  roles:

    - role: dreknix.user.bin
      tags:
        - user
        - user_bin

    - role: dreknix.user.packages
      tags:
        - user
        - user_packages

    - role: dreknix.user.gnome
      tags:
        - user
        - user_gnome

    - role: dreknix.user.tmux
      tags:
        - user
        - user_tmux

    - role: dreknix.user.vim
      tags:
        - user
        - user_vim

    - role: dreknix.user.zsh
      tags:
        - user
        - user_zsh

...
